// Complete Expanded Restaurant Directory
const restaurantList = [
"211 Clover Lane”,
"Abol Cafe (Coffee + Kitchen)”,
"AJ Subs LLC”,
"Ala Eh Eats Filipino Food and Sushi”,
"ALDI”,
"All Thai’d Up”,
"Anar Food Mart”,
"Arby's”,
"Asahi Japanese Restaurant”,
"Bahn Thai & M”,
"Bamboo Coffee & Donuts”,
"Bandido Taqueria Mexicana”,
"Barry Bagels”,
"Basilico Cafe”,
"Baskin-Robbins”,
"Bearnos Pizza”,
"Better Blend - Louisville”,
"Biscuit Belly: Louisville - St. Matthews”,
"BJ's Restaurant & Brewhouse”,
"Blaze Pizza”,
"BOMBAY GRILL - INDIAN RESTAURANT”,
"Bonefish Grill”,
"BoomBozz Pizza & Watch Bar”,
"Bourbon & Burger”,
"Brasserie Provence”,
"Brick House Tavern + Tap”,
"Bristol Bar & Grille | East”,
"Bruegger's Bagels”,
"Buffalo Wild Wings”,
"Burger Girl”,
"California Pizza Kitchen at Oxmoor”,
"Carniceria Butcher Shop”,
"Carrabba's Italian Grill”,
"CASK Southern Kitchen & Bar”,
"Charleys Cheesesteaks”,
"Cheddar Box Too”,
"Cheddar's Scratch Kitchen”,
"Chef's Cut Pizzeria”,
"Chicken Salad Chick”,
"Chick-fil-A”,
"Chili's Grill & Bar”,
"China 1”,
"China 1 - Lyndon”,
"China Star”,
"Choi's Asian Food Market”,
"Chipotle”,
"Chuy's”,
"Cinnaholic”,
"Cinnabon”,
"Circle K”,
"City Barbeque”,
"Coals Artisan Pizza”,
"Cold Stone Creamery”,
"Con Huevos! - Breakfast & Brunch”,
"Condado Tacos”,
"Connors Steak & Seafood”,
"Craft House Pizza - Westport”,
"Crumbl Cookies”,
"Currito Louisville”,
"Dave & Buster's Louisville”,
"Dave's Hot Chicken”,
"Del Frisco's”,
"DiOrio's Pizza & Pub”,
"District 6”,
"Domino's Pizza”,
"Drake's - St. Matthews”,
"Dunkin Donuts”,
"Eat A Pita”,
"Elderberry Provisions”,
"El Mariachi Mexican Restaurant”,
"El Nopal - Mall St. Matthews”,
"El Nopal Mexican Food | Westport Rd”,
"El Tarasco”,
"Fazoli's”,
"Felipe's Mexican Kitchen”,
"Fire House subs”,
"First Watch”,
"The Fishery”,
"Five Guys”,
"Food Court @ Mall St. Matthews”,
"Ginza Asian Bistro”,
"Graeter's Ice Cream”,
"Grassa Gramma”,
"Green District Salads - St. Matthews”,
"Gus's World Famous Fried Chicken”,
"Gustavo's Mexican Grill”,
"Half-Peach Bakery & Cafe”,
"Heine Brothers' Coffee - Chenoweth Lane”,
"Heitzman Traditional Bakery and Deli”,
"Highland Morning St. Matthews”,
"hiko-A-mon”,
"Hillcrest Tavern”,
"Hooters”,
"IHOP”,
"Impellizzeri's Pizza”,
"J. Alexander's Restaurant”,
"Jack in the Box”,
"Jade Palace”,
"Jaggers”,
"Jasmine Asian Bistro”,
"Jason's Deli”,
"Jeff's Donuts”,
"Jersey Mike's Subs”,
"Jet's Pizza”,
"Jimmy John's Gourmet Sandwiches”,
"Joe’s Older Than Dirt”,
"Joella's Hot Chicken - St. Matthews”,
"JOJO GYROS 2”,
"KFC”,
"King Donuts Lyndon”,
"King Gyros - St. Matthew’s Mall”,
"Kingfish”,
"Kroger”,
"Kupbop Korean Bbq”,
"La Cocina de Mama”,
"La Rosita Sol”,
"Las Maria”,
"Lee's Famous Recipe Chicken”,
"Lemongrass Cafe and Market”,
"Limón y Sal Mexican Kitchen”,
"Little Greek Fresh Grill”,
"Los Aztecas Mexican Restaurant”,
"Lotsa Pasta”,
"Lou Lou Food & Drink”,
"Maira Mediterranean Grill”,
"McAlister's Deli”,
"McDonald's”,
"Mesh Louisville”,
"MISSION BBQ”,
"Mojito in Havana”,
"Mojito Tapas Restaurant”,
"Momma's BBQ”,
"Nam Nam Café”,
"Noodles and Company”,
"Noosh Nosh”,
"North Lime Coffee & Donuts”,
"Nothing Bundt Cakes”,
"Olive Garden”,
"Oriental House”,
"Osteria Del Mar”,
"Osteria Italian Seafood”,
"P.F. Chang's”,
"Panda Express”,
"Panaderia Bakery”,
"Panera Bread”,
"Papa Johns”,
"Paris Baguette”,
"Paul's Fruit Market”,
"Penn Station”,
"Pho Phi Louisville”,
"Pizza Hut”,
"Pizza Jones”,
"Pizzaville”,
"Playa Bowls”,
"Plehn's Bakery”,
"QDOBA Mexican Eats”,
"R Place Pub”,
"Rafferty's Restaurant & Bar”,
"Raising Cane's”,
"Rainbow Blossom St Matthews”,
"Ramsi's Cafe On The World”,
"Raymi Peruvian and Mexican Cuisine”,
"Red Lobster”,
"RedBrick Pizza”,
"Red Robin Gourmet Burgers and Brews”,
"River House Restaurant and Raw Bar”,
"Ruby Thai Kitchen - St. Matthews Mall”,
"Saints Pizza Pub & SkyBar”,
"Sakura Blue”,
"Salsarita's Fresh Mexican Grill”,
"Selena's at Willow Lake Tavern”,
"Shady Lane Cafe”,
"Shawarma Shack”,
"Shiraz Mediterranean Grill”,
"Silvio's Italian Restaurant”,
"Simply Thai”,
"Skyline Chili”,
"Smashburger”,
"Speedway”,
"Squeeze The Day”,
"Starving Artists Cafe & Deli”,
"Subway”,
"Sunergos Coffee”,
"Supermercado Guanajuato #1”,
"Taco Bell”,
"Taco Choza”,
"Taco Luchador”,
"Taco N Madres”,
"Taco Stand”,
"Taziki's Mediterranean Cafe”,
"Ten Pin Strike & Spare”,
"Texas Roadhouse”,
"The Charcoal Restaurant”,
"The Cheesecake Factory”,
"The Comfy Cow”,
"The Deli - Willis Ave”,
"The Eagle Oxmoor”,
"The Fresh Market”,
"The Goose Eatery & Hangout”,
"The Honey Baked Ham Company”,
"The Lyndon Station Bar and Grill”,
"The Pie Kitchen”,
"Thorntons”,
"TIKKA HOUSE INDIAN RESTAURANT”,
"Tin Roof”,
"ToGo Sushi”,
"Tokyo Japanese Restaurant”,
"Topgolf Louisville”,
"Tortilleria GuanaJuato”,
"Trader Joe's”,
"Tres Amigos Of Louisville”,
"Twin Peaks”,
"W W Cousins Restaurant”,
"Waffle House”,
"Walmart Neighborhood Market”,
"Wasabi Louisville”,
"Wendy's”,
"Which Wich Superior Sandwiches”,
"White Castle”,
"Whole Foods Market”,
"Wild Eggs”,
"Wingstop"
];
